name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    if: github.event.commits.*.modified || github.event.commits.*.added || github.event.commits.*.removed

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the API
        run: pnpm run build